### ISSUE TITLE
TypeError: Not a buffer

### ISSUE THREAD

**Issue by dotmilk** [senecajs-labs/seneca-dynamo-store#3]
So, after getting past the previous error I get this. I tested my config of secret key endpoint etc with the plain ddb package that this depends on. And it works as expected.

```
TypeError: Not a buffer
    at new Hmac (crypto.js:257:17)
    at Object.Hmac (crypto.js:255:12)
    at auth (/Users/emris/htqkly/AppTrackerRefactor/node_modules/seneca-dynamo-store/node_modules/dynamodb/lib/ddb.js:1010:23)
    at execute (/Users/emris/htqkly/AppTrackerRefactor/node_modules/seneca-dynamo-store/node_modules/dynamodb/lib/ddb.js:849:5)
    at EventEmitter.scan (/Users/emris/htqkly/AppTrackerRefactor/node_modules/seneca-dynamo-store/node_modules/dynamodb/lib/ddb.js:706:5)
    at Seneca.store.load (/Users/emris/htqkly/AppTrackerRefactor/node_modules/seneca-dynamo-store/lib/dynamodb-store.js:192:20)
    at Object.execspec.fn (/Users/emris/htqkly/AppTrackerRefactor/node_modules/seneca/seneca.js:1497:24)
    at Object._onImmediate (/Users/emris/htqkly/AppTrackerRefactor/node_modules/seneca/node_modules/gate-executor/gate-executor.js:108:14)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by dotmilk** [comment]
Also, is there a reason endpoint is being ignored in your package? the line is commented out.

**Comment by dotmilk** [comment]
so found error was related to a disparity between documentation and implementation:

```
      accessKeyId: 'ACCESSKEYID',
      secretAccessKey: 'SECRETACCESSKEY',
      endpoint: 'ENDPOINT'
```

when I changed config to match 

```
    var conf = 'string' == typeof(spec) ? null : spec;
    connection = dynamodb.ddb({accessKeyId: conf.keyid,
                               secretAccessKey: conf.secret,
                              endpoint: conf.endpoint});
    seneca.log.debug('init', 'db open', spec);
    cb(null);
```

everything worked, also required uncommenting out endpoint from the connection config.

**Comment by jreeter** [comment]
pretty frustrating the owner doesn't seem to take care of this repo. It's time to fork and make an active version.

**Comment by darsee** [comment]
Hi @jreeter - I understand your frustration and you're right, I have been neglecting this. I have two young children so I don't have much time for open source these days... Maybe @vtardia knows someone who could take a look?

**Comment by vtardia** [comment]
Hi @jreeter  - I've updated the master branch with our latest work. A lot has changed and it works with latest versions of seneca. Give it a try and let me know if you still have errors.
